name: HH Multicall Autorenew Mainnet

on:
  schedule:
    - cron: "11 2/14 * * *"

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-function:
    runs-on: ubuntu-latest # small, quick-to-start runner

    steps:
      - name: Check out repository (with full history & write access)
        uses: actions/checkout@v3
        with:
          # Fetch everything, not just one commit (needed for pushes)
          fetch-depth: 0
          # Persist the GITHUB_TOKEN into .git/config so that git push works
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install ethers @evmlord/multicall-sdk tsx

      - name: Call smart contract function (and regenerate cache)
        env:
          HH_PRIVATE_KEY: ${{ secrets.HH_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.HHLOGS_TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.HHLOGS_TG_CHATID }}
        run: npx tsx HHV2/multicall-10x-main.ts

        # — now commit+push the updated cache file —
      - name: Configure Git for Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or reset cache branch
        run: |
          git fetch origin main
          # use the same branch name each run
          git checkout -B cache/update-wallets-10x-main-cache origin/main

      - name: Force commit cache file (always commit)
        run: |
          if [ -f HHV2/wallets-10x-main-cache.json ]; then
            git add HHV2/wallets-10x-main-cache.json
            git commit -m "chore: update wallets-10x-main-cache.json [ci skip]" || echo "No changes to commit."
            git push --set-upstream origin cache/update-wallets-10x-main-cache --force
          else
            echo "❌ wallets-10x-main-cache.json not found. Skipping commit."
          fi

      - name: Open (or update) Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const BRANCH = "cache/update-wallets-10x-main-cache";
            const REVIEWERS = ["EVMlord"];           // ⇦ GitHub usernames

            // look for an open PR whose head is this exact branch **in this repo**
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${BRANCH}`,  // owner + ':' + branch
              state: "open",
            });

            let pr; // will always have a .data property
            if (prs.length === 0) {
              pr = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "chore: update wallets-10x-main-cache.json [ci skip]",
                head: BRANCH,
                base: "main",
                body: "This PR was auto-generated by the HH Multicall Autorenew workflow.",
              });
              console.log("Opened PR:", pr.data.html_url);
            } else {
              pr = { data: prs[0] }; // normalize shape to match create() response
              console.log("PR already open:", pr.data.html_url);
            }

            // ask for review
            // don't request review from the PR author
            const author = pr.data.user.login;
            const reviewers = REVIEWERS.filter(u => u && u !== author);

            if (reviewers.length > 0) {
              try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo:  context.repo.repo,
                pull_number: pr.data.number,
                reviewers,       // users
              });
              console.log("Review requested from:", [...reviewers].join(", "));
            } catch (e) {
              // 422 = reviewers already requested — safe to ignore
              if (e.status !== 422) throw e;
              console.log("Reviewers already requested, skipping.");
            }
            } else {
             console.log("No eligible reviewers to request.");
             }
